name: Interval Merge

on:
  push:
    paths:
      - 'interval_merge/**'
  pull_request:
    paths:
      - 'interval_merge/**'

jobs:
  javascript:
    # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # Interval Merge requires >=17, 17 is eof
        node-version: ['18.*', '20.*', 'latest']
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: node interval_merge/javascript/merge.js
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: interval_merge/rust
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Use stable since Rust is forwards-compatibility
          # and the code should keep compiling with newer versions.
          # Rust std is the only dependency.
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --tests --all-features -- -D warnings
      - run: cargo test --verbose --all-features 
  go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: interval_merge/go
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build
      run: go build -v
    - name: Test
      run: go test -v
    - name: Benchmark
      run: go test -v -bench Benchmark*
